version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.11-browsers
    working_directory: ~/repo
    environment:
    - SOURCE_BRANCH: master
    - TARGET_BRANCH: master
    - TERM: xterm
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
        - "9d:2d:19:e3:23:f5:19:02:2d:ac:2b:2c:3e:ba:ab:d0"
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: npm ci
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: npm run build:gh
    - deploy:
        name: Deploy
        command: bash ./deploy.sh
workflows:
  version: 2
  workflow:
    jobs:
    - build:
        filters:
          branches:
            ignore:
            - gh-page